version: "3"
services:
  # MongoDB services
  mongo:
        image: mongo:5.0.9
        volumes:
                - mongo_db:/data/db
                - ./mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
                - ./cve_db_dump:/cve_db_dump
        ports:
              - 27018:27017
        container_name: mongo_container

  # Flask rest-api application       
  api:
      build:
            dockerfile: api.Dockerfile
            context: .
      ports:
              - 5000:5000
      container_name: rest_api
      environment:
                MONGODB_URI: mongodb://mongo:27017
                DB_NAME: cve_db
      depends_on: 
                - mongo  

volumes:
        mongo_db: {}