version: "3"
services:
  # MongoDB services
  mongo:
        image: mongo:5.0.9
        volumes:
                - mongo_db:/data/db
                - ./mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
                - ./cve_db_dump:/cve_db_dump
        ports:
              - 27018:27017
        container_name: mongo_container

  # Flask rest-api application       
  api:
      build:
            dockerfile: api.Dockerfile
            context: .
      ports:
              - 5001:5000
      container_name: rest_api
      environment:
                DB_NAME: cve_db
                SECRET_KEY: fb98948b17624333a35ab22a5ac328f7
                MONGO_TEST_URI: mongodb://mongo:27017/test_cve_db
                MONGO_URI: mongodb://mongo:27017/cve_db
                MONGO_HOST: mongo

      depends_on: 
                - mongo  

volumes:
        mongo_db: {}